[package]
name = "turing-machine"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
strip = "symbols"
opt-level = 3
codegen-units = 1
debug = 0
split-debuginfo = "packed"


[dependencies]
